### ISSUE TITLE
Scoped packages not being passed to custom resolver

### ISSUE THREAD

**Issue by josh-hemphill** [garronej/denoify#51]
I was trying to work with the custom resolver to add all the polyfills/forks for packages, and realized it never resolved any of the namespaced packages.
I've been trying to see if I can get Tedious working in deno (since having mssql support in deno would be huge) and most of the dependencies work grabbing them from esm.sh, but the ones under `@azure/` and `@js-joda` never come through the custom resolver for me to be able to replace.

**Comment by garronej** [comment]
Hi @josh-hemphill,  
Sorry if there is a bug with the custom replacers.  They are already quite hard to work with, if there is bugs on top of it... 
Could you:  
1) Provide some example of the imports statement you have in the source codebase and what would be the expected output.  
2) (Optional) If you could fork [this demo repo](https://github.com/garronej/my_dummy_npm_and_deno_module) and put what you have tried already.  

Best

**Comment by josh-hemphill** [comment]
Here's the fork of the demo repo, not sure what else to add other than a replacement in the resolver.
Though I also added a console log to it so you can see that none of them include namespaced packages.
For the `@azure/identity` the generated code has `@azure/identity DENOIFY: DEPENDENCY UNMET (BUILTIN)`
The source was 
```ts
import {
  DefaultAzureCredential,
  ClientSecretCredential,
  ManagedIdentityCredential,
  UsernamePasswordCredential,
} from '@azure/identity';
```
But it's not multi-line related since the same thing happens with 
```ts
import { ChronoUnit, LocalDate } from '@js-joda/core';
```

**Comment by garronej** [comment]
I can reproduce. I'll address it.

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/183690798-b2bd2db1-7dcf-46f1-9420-ab8874e9dfdb.png)

It has been fixed in the last version of Keycloakify, thank you for reporting.

**Comment by josh-hemphill** [comment]
Awesome! Thanks

It looks like I'm still getting node modules being replaced with `DENOIFY: DEPENDENCY UNMET (BUILTIN)`, is there a config I'm missing to be able to set those to use the incomplete deno_std compat shims?

**Comment by josh-hemphill** [comment]
If I add an `import dns from 'dns'` to the demo repo with the updated denoify, with or without a manual port/replacement, it always generates `import dns from 'dns DENOIFY: DEPENDENCY UNMET (BUILTIN)'`.
